name: Build NymphOS SRPMs (Ubuntu)

on:
  workflow_dispatch: # Manual trigger only

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm rpm-build gcc make patch tar xz bzip2 gzip \
            binutils libelf-dev openssl libssl-dev zlib1g-dev \
            libncurses5-dev perl python3 python3-dev bc bison flex \
            libtool autoconf automake pkg-config git libmnl-dev \
            libcap-ng-dev libselinux1-dev libkmod-dev libaudit-dev \
            pciutils libudev-dev libmount-dev e2fsprogs-dev libblkid-dev \
            libdevmapper-dev libnl-3-dev libcap-dev libtirpc-dev \
            libseccomp-dev libbpf-dev

      - name: Build Linux Kernel SRPM
        run: |
          mkdir tmp-kernel
          cp tarballs/linux/linux-*.tar.xz tmp-kernel/
          cd tmp-kernel
          tar xf linux-*.tar.xz
          cd linux-*
          cp ../../../specs/linux/.config .config
          rpmbuild -bs ../../../specs/linux/*.spec
          mkdir -p ../../../srpms/linux
          mv ../../../rpmbuild/SRPMS/*.src.rpm ../../../srpms/linux/
          cd ../..
          rm -rf tmp-kernel

      - name: Build Dracut SRPM
        run: |
          mkdir tmp-dracut
          cp tarballs/dracut/dracut-*.tar.gz tmp-dracut/
          cd tmp-dracut
          tar xf dracut-*.tar.gz
          cd dracut-*
          rpmbuild -bs ../../../specs/dracut/*.spec
          mkdir -p ../../../srpms/dracut
          mv ../../../rpmbuild/SRPMS/*.src.rpm ../../../srpms/dracut/
          cd ../..
          rm -rf tmp-dracut

      - name: Build Syslinux SRPM
        run: |
          mkdir tmp-syslinux
          cp tarballs/syslinux/syslinux-*.tar.xz tmp-syslinux/
          cd tmp-syslinux
          tar xf syslinux-*.tar.xz
          cd syslinux-*
          rpmbuild -bs ../../../specs/syslinux/*.spec
          mkdir -p ../../../srpms/syslinux
          mv ../../../rpmbuild/SRPMS/*.src.rpm ../../../srpms/syslinux/
          cd ../..
          rm -rf tmp-syslinux

      - name: Build OpenRC SRPM
        run: |
          mkdir tmp-openrc
          cp tarballs/openrc/openrc-*.tar.gz tmp-openrc/
          cd tmp-openrc
          tar xf openrc-*.tar.gz
          cd openrc-*
          rpmbuild -bs ../../../specs/openrc/*.spec
          mkdir -p ../../../srpms/openrc
          mv ../../../rpmbuild/SRPMS/*.src.rpm ../../../srpms/openrc/
          cd ../..
          rm -rf tmp-openrc

      - name: Upload SRPMs
        uses: actions/upload-artifact@v4
        with:
          name: srpms
          path: srpms/
          retention-days: 7
